name: Push to ECR

on:
  push:
    branches:
      - master  # change this to the branch you want to trigger the action on

jobs:
  push_to_ecr:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1

      - name: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654507153.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build -t kamal .
          docker tag kamal:latest 654654507153.dkr.ecr.us-east-1.amazonaws.com/kamal:latest

      - name: Push image to ECR
        run: docker push 654654507153.dkr.ecr.us-east-1.amazonaws.com/kamal:latest
